### ISSUE TITLE
Script para pegar as informações dos jogos

### ISSUE THREAD

**Issue by ednunes** [eduardonunes2525/unbgames-platform#17]
**Tarefas**

- [ ] Criar política de atualização dos metadados dos jogos.
- [ ] Definir o template que os desenvolvedores deverão preencher para terem seus jogos na plataforma.
- [ ] Fazer um parser do arquivo que contém as informações dos jogos.
- [ ] Criar o script de atualização das informações dos jogos.
